package com.todoapp.uikit.theme

import androidx.compose.runtime.Immutable
import androidx.compose.runtime.staticCompositionLocalOf
import androidx.compose.ui.graphics.Color

internal val LocalLightColors = staticCompositionLocalOf { lightColors() }
internal val LocalDarkColors = staticCompositionLocalOf { darkColors() }

internal fun lightColors(
    infoCardBgColor: Color = Color(0xFFEEF2FF),
    groupMemberCardBgColor: Color = Color(0xFFEBEBEB),
    groupTaskFilterColor: Color = Color(0xFFFF0000),
    lightRed: Color = Color(0xFFFFE6E7),
    red: Color = Color(0xFFFFB1B5),
    crossRed: Color = Color(0xFFB2282D),
    statusCardGray: Color = Color(0xFF6E7180),
    bgColorPurple: Color = Color(0xFFEFF2FF),
    bgColor: Color = Color(0xFFF8F9FC),
    background: Color = bgColor,
    onBackground: Color = Color(0xFF090E23),
    surface: Color = Color(0xFFFFFAF0),
    onSurface: Color = Color(0xFF090E23),
    primary: Color = Color(0xFF4566EC),
    onPrimary: Color = Color(0xFFFFFAF0),
    lightPurple: Color = Color(0xFFA9BAFF),
    gray: Color = Color(0xFF717171),
    darkPurple: Color = Color(0xFF1C3082),
    purple: Color = Color(0xFF4566EC),
    black: Color = Color(0xFF090E23),
    brown: Color = Color(0xFF3F2D20),
    green: Color = Color(0xFF2AE35A),
    lightGreen: Color = Color(0xFFE8F5E9),
    mediumGreen: Color = Color(0xFF81C784),
    darkGreen: Color = Color(0xFF2E7D32),
    orange: Color = Color(0xFFEF8829),
    darkBrown: Color = Color(0xFF73665C),
    lightBrown: Color = Color(0xFFD3BBAA),
    beige: Color = Color(0xFFE6DCCD),
    lightOrange: Color = Color(0xFFFFE2CD),
    lightYellow: Color = Color(0xFFFFF8E1),
    lightPending: Color = Color(0xFFEDF4FF),
    mediumPending: Color = Color(0xFF4E90C4),
    pendingGray: Color = Color(0xFF7A9CC6),
    darkPending: Color = Color(0xFF3D6A9E),
    white: Color = Color(0xFFFFFAF0),
    softPink: Color = Color(0xFFF5D3BB),
    lightGray: Color = Color(0xFFC0C0C0),
): TDColor =
    TDColor(
        infoCardBgColor = infoCardBgColor,
        groupMemberCardBgColor = groupMemberCardBgColor,
        groupTaskFilterColor = groupTaskFilterColor,
        lightRed = lightRed,
        red = red,
        crossRed = crossRed,
        statusCardGray = statusCardGray,
        bgColorPurple = bgColorPurple,
        bgColor = bgColor,
        background = background,
        onBackground = onBackground,
        surface = surface,
        onSurface = onSurface,
        primary = primary,
        onPrimary = onPrimary,
        gray = gray,
        black = black,
        darkPurple = darkPurple,
        purple = purple,
        brown = brown,
        green = green,
        lightGreen = lightGreen,
        mediumGreen = mediumGreen,
        darkGreen = darkGreen,
        orange = orange,
        darkBrown = darkBrown,
        lightBrown = lightBrown,
        beige = beige,
        lightOrange = lightOrange,
        lightYellow = lightYellow,
        lightPending = lightPending,
        mediumPending = mediumPending,
        pendingGray = pendingGray,
        darkPending = darkPending,
        white = white,
        softPink = softPink,
        lightGray = lightGray,
        lightPurple = lightPurple,
    )

internal fun darkColors(
    infoCardBgColor: Color = Color(0xFF1E2240),
    groupMemberCardBgColor: Color = Color(0xFF232323),
    groupTaskFilterColor: Color = Color(0xFFFF0000),
    lightRed: Color = Color(0xFF7A1F2B),
    red: Color = Color(0xFFFFB1B5),
    crossRed: Color = Color(0xFFCF6679), // Standard Material Dark Error
    statusCardGray: Color = Color(0xFF898DA1),
    bgColorPurple: Color = Color(0xFF2B2F5E),
    bgColor: Color = Color(0xFF121212),
    background: Color = Color(0xFF16171B),
    onBackground: Color = Color(0xFFE1E1E1),
    surface: Color = Color(0xFF1E1E1E),
    onSurface: Color = Color(0xFFE1E1E1),
    primary: Color = Color(0xFF6C8AFF), // Lighter primary for dark mode
    onPrimary: Color = Color(0xFF000000),
    lightPurple: Color = Color(0xFFA9BAFF),
    gray: Color = Color(0xFF9E9E9E),
    darkPurple: Color = Color(0xFF1C3082),
    purple: Color = Color(0xFF4566EC),
    black: Color = Color(0xFF000000),
    brown: Color = Color(0xFF3F2D20),
    green: Color = Color(0xFF84BD93),
    lightGreen: Color = Color(0xFF1B3A1E),
    mediumGreen: Color = Color(0xFF4CAF50),
    darkGreen: Color = Color(0xFFA5D6A7),
    orange: Color = Color(0xFFEF8829),
    darkBrown: Color = Color(0xFF73665C),
    lightBrown: Color = Color(0xFFD3BBAA),
    beige: Color = Color(0xFFE6DCCD),
    lightOrange: Color = Color(0xFFFFE2CD),
    lightYellow: Color = Color(0xFFFFF5E0),
    lightPending: Color = Color(0xFF1A2537),
    mediumPending: Color = Color(0xFF3A93DB),
    pendingGray: Color = Color(0xFF6B8DB5),
    darkPending: Color = Color(0xFF9BBDE0),
    white: Color = Color(0xFFFFFAF0),
    softPink: Color = Color(0xFFF5D3BB),
    lightGray: Color = Color(0xFF444444),
): TDColor =
    TDColor(
        infoCardBgColor = infoCardBgColor,
        groupMemberCardBgColor = groupMemberCardBgColor,
        groupTaskFilterColor = groupTaskFilterColor,
        lightRed = lightRed,
        red = red,
        crossRed = crossRed,
        statusCardGray = statusCardGray,
        bgColorPurple = bgColorPurple,
        bgColor = bgColor,
        background = background,
        onBackground = onBackground,
        surface = surface,
        onSurface = onSurface,
        primary = primary,
        onPrimary = onPrimary,
        gray = gray,
        black = black,
        purple = purple,
        darkPurple = darkPurple,
        brown = brown,
        green = green,
        lightGreen = lightGreen,
        mediumGreen = mediumGreen,
        darkGreen = darkGreen,
        orange = orange,
        darkBrown = darkBrown,
        lightBrown = lightBrown,
        beige = beige,
        lightOrange = lightOrange,
        lightYellow = lightYellow,
        lightPending = lightPending,
        mediumPending = mediumPending,
        pendingGray = pendingGray,
        darkPending = darkPending,
        white = white,
        softPink = softPink,
        lightGray = lightGray,
        lightPurple = lightPurple,
    )

@Immutable
data class TDColor(
    val infoCardBgColor: Color,
    val groupMemberCardBgColor: Color,
    val groupTaskFilterColor: Color,
    val lightRed: Color,
    val red: Color,
    val crossRed: Color,
    val statusCardGray: Color,
    val bgColorPurple: Color,
    val bgColor: Color,
    val background: Color,
    val onBackground: Color,
    val surface: Color,
    val onSurface: Color,
    val primary: Color,
    val onPrimary: Color,
    val lightPurple: Color,
    val gray: Color,
    val black: Color,
    val darkPurple: Color,
    val purple: Color,
    val brown: Color,
    val green: Color,
    val lightGreen: Color,
    val mediumGreen: Color,
    val darkGreen: Color,
    val orange: Color,
    val darkBrown: Color,
    val lightBrown: Color,
    val beige: Color,
    val lightOrange: Color,
    val lightYellow: Color,
    val lightPending: Color,
    val mediumPending: Color,
    val pendingGray: Color,
    val darkPending: Color,
    val white: Color,
    val softPink: Color,
    val lightGray: Color,
)
